createProduct:
  handler: src/product/handler/product-create-handler.productCreateHandler
  events:
    - http:
        path: product
        method: post
updateProduct:
  handler: src/product/handler/product-update-handler.productUpdateHandler
  events:
    - http:
        path: product/{productId}
        method: post
deleteProduct:
  handler: src/product/handler/product-delete-handler.productDeleteHandler
  events:
    - http:
        path: product/{productId}
        method: delete
getProductById:
  handler: src/product/handler/product-get-by-id-handler.productGetByIdHandler
  events:
    - http:
        path: product/{productId}
        method: get
listProducts:
  handler: src/product/handler/product-list-handler.productListHandler
  events:
    - http:
        path: product
        method: get
