version: '3.8'

services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: degget
      POSTGRES_PASSWORD: beaver
      POSTGRES_DB: lian
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: degget@lian.com
      PGADMIN_DEFAULT_PASSWORD: beaver
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4571:4571"  # external services port range
    environment:
      - SERVICES=s3
      - DEBUG=1
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"


volumes:
  local_pgdata:
  pgadmin-data:
